/**:
  ros__parameters:
    update_rate: 100  # Hz

    t42_right_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    t42_left_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    t42_gripper_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    t42_joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

t42_right_trajectory_controller:
  ros__parameters:
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    joints:
      - swivel_1_to_finger_1_1
      - finger_1_1_to_finger_1_2
    allow_partial_joints_goal: false

t42_left_trajectory_controller:
  ros__parameters:
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    joints:
      - swivel_2_to_finger_2_1
      - finger_2_1_to_finger_2_2
    allow_partial_joints_goal: false

t42_gripper_controller:
  ros__parameters:
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    joints:
      - swivel_1_to_finger_1_1
      - finger_1_1_to_finger_1_2
      - swivel_2_to_finger_2_1
      - finger_2_1_to_finger_2_2
