controller_names:
  - joint_trajectory_controller

joint_trajectory_controller:
  action_ns: follow_joint_trajectory
  type: FollowJointTrajectory
  default: true
  joints:
    - swivel_1_to_finger_1_1
    - swivel_2_to_finger_2_1
    - finger_1_1_to_finger_1_2
    - finger_2_1_to_finger_2_2

