controller_names:
  - t42_right_trajectory_controller
  - t42_left_trajectory_controller
  - t42_gripper_controller


t42_right_trajectory_controller:
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: false
    joints:
      - swivel_1_to_finger_1_1
      - finger_1_1_to_finger_1_2
t42_left_trajectory_controller:
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: false
    joints:
      - swivel_2_to_finger_2_1
      - finger_2_1_to_finger_2_2

t42_gripper_controller:
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - swivel_2_to_finger_2_1
      - finger_2_1_to_finger_2_2
      - swivel_1_to_finger_1_1
      - finger_1_1_to_finger_1_2
